# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ vars.RAILWAY_SVC_ID }}
      PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4

      # - name: Link Railway Project
      #   run: railway link $PROJECT_ID

      # - name: Debug Railway Status
      #   run: railway status

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }} --detach
        # run: railway up --service=$SVC_ID

      # - name: Redeploy in Railway
      #   run: railway redeploy --service=$SVC_ID
